[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm build",
  "cd docs && pnpm install --frozen-lockfile",
  "cd docs && pnpm build"
]

[start]
cmd = "cd docs && pnpm start"
