[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter annota build", "pnpm --filter annota-docs build"]

[start]
cmd = "cd docs && pnpm start"
