[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@10.15.0",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm --filter annota build",
  "pnpm --filter annota-docs build"
]

[start]
cmd = "cd docs && npx serve@latest out"
